[package]
name = "simplan"
version = "0.1.0"
edition = "2024"

[features]
# Enable Bevy's dynamic linking for faster incremental builds during development.
# Do NOT enable this in release builds.
dev = ["bevy/dynamic_linking"]

[dependencies]
avian3d = "0.2"
bevy = { version = "0.15" }
fdm     = { path = "../fdm" }
terrain = { path = "../terrain" }
geodata = { path = "../geodata" }
